#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# do only execute for Debian and similar distros
if ! ifclass DEBIAN ; then
    exit 0
fi

set -a

# do not set up grub during dirinstall
if [ "$FAI_ACTION" = "dirinstall" ] ; then
    exit 0
fi
# during softupdate use this file
[ -r $LOGDIR/disk_var.sh ] && . $LOGDIR/disk_var.sh

if [ -z "$BOOT_DEVICE" ]; then
    exit 189
fi

# skip the rest, if not an initial installation
if [ $FAI_ACTION != "install" ]; then
    $ROOTCMD update-grub
    exit $error
fi

GROOT=$($ROOTCMD grub-probe -tdrive -d $BOOT_DEVICE)

# ARM64 or AMD64
arch=$(uname -m)
if [ "$arch" == "aarch64" ]; then
    opts="--no-floppy --modules=part_gpt"
else
    opts="--no-floppy --target=x86_64-efi --modules=part_gpt"
fi

if ifclass FBREMOVABLE ; then
    # ensure booting from thunderbolt disks works
    # with security=user
    # by not resetting the thunderbolt controller
    fcopy -m root,root,0644 -v /etc/default/grub.d/90_thunderbolt.cfg

    # ensure /boot/efi/EFI/debian not being created or 
    # being removed if created on removable grub install
    # as well as no efi boot entry being created
    # now and 
    # on every apt, dpkg, dpkg-reconfigure action
    # (only required on pkg grub-efi-amd64, 
    # but hard to filter)
    fcopy -m root,root,0644 -v /etc/dpkg/dpkg.cfg.d/99-efi-fallback-only
    fcopy -m root,root,0755 -v /usr/local/bin/efi-grub-debconf-enforce
    fcopy -m root,root,0755 -v /usr/local/bin/efi-rm-debian-dir
    opts="${opts} --removable"
fi

if ifclass FBDESKTOP ; then
    fcopy -m root,root,0644 -v /etc/default/grub.d/90_splash.cfg
    $ROOTCMD plymouth-set-default-theme bgrt -R
fi

$ROOTCMD grub-install $opts "$GROOT"
if [ $? -eq 0 ]; then
    echo "Grub installed on $BOOT_DEVICE = $GROOT"
fi

$ROOTCMD update-grub
if [[ $BOOT_DEVICE =~ '/dev/loop' ]]; then
    :
else
    efibootmgr -v
fi

exit $error
