#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# remove crypt password from variables.log
if [ -f $LOGDIR/variables.log ]; then
    perl -i -pane "s/CRYPTPW=.*$/CRYPTPW=XXXXXXXXXXXXX/g" $LOGDIR/variables.log
fi

